version: '3'
services:
  postgres:
    image: jie123108/postgres-imgsmlr
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - PGDATA=/data/docker/psql-imgsmlr-test
    volumes:
      - ./scripts/imgsmlr_init.sql:/docker-entrypoint-initdb.d/imgsmlr_init.sql
  server:
    image: jie123108/imgsmlr-server:latest
    ports:
      - 8140:8140
    depends_on:
      - postgres
    environment:
      - POSTGRESQL_URL=postgresql+asyncpg://imgsmlr:imgsmlr-123456@postgres:5400/imgsmlr
      - SEARCH_LIMIT=3
      - SEARCH_SIMR_THRESHOLD=1.2
    entrypoint: /opt/app-root/bin/uvicorn
    command: img-smlr-server:app --backlog 2048 --host=0.0.0.0 --port=8140
    volumes:
      - /data:/data
